"""Hand-authored spatial fixtures. They are not generated by a language model."""

import json
from dataclasses import dataclass
from importlib.resources import files

from world.schema import MapSpec, ObjectAttributes, ObjectToken, RelationToken, WorldState


@dataclass(frozen=True)
class Scenario:
    name: str
    prompt: str
    expected_counts: dict[str, int]


def load_scenarios() -> list[Scenario]:
    data = json.loads(files("examples").joinpath("prompts.json").read_text(encoding="utf-8"))
    return [Scenario(**item) for item in data]


def _obj(kind, number, x, y, w=1, h=1, style=None):
    return ObjectToken(
        object_type=kind,
        id=f"{kind}_{number:03d}",
        position=[x, y],
        attributes=ObjectAttributes(size=[w, h], style=style),
    )


def _rel(kind, source, target):
    return RelationToken(relation_type=kind, source=source, target=target)


def fixture_worlds() -> dict[str, WorldState]:
    forest = WorldState(
        scene="dark_forest_village",
        map=MapSpec(biome="forest"),
        objects=[
            _obj("river", 1, 17, 0, 2, 24),
            _obj("road", 1, 3, 12, 14, 2),
            _obj("road", 2, 19, 12, 10, 2),
            _obj("bridge", 1, 17, 12, 2, 2),
            _obj("house", 1, 5, 6, 3, 3, "wood"),
            _obj("house", 2, 10, 5, 3, 3, "wood"),
            _obj("house", 3, 8, 16, 3, 3, "wood"),
            _obj("monster", 1, 24, 7),
            _obj("monster", 2, 25, 17),
            *[
                _obj("tree", n, x, y)
                for n, (x, y) in enumerate(
                    [
                        (2, 2),
                        (6, 2),
                        (13, 2),
                        (22, 2),
                        (28, 3),
                        (2, 7),
                        (2, 19),
                        (4, 21),
                        (13, 20),
                        (22, 21),
                        (29, 20),
                        (28, 9),
                    ],
                    1,
                )
            ],
        ],
        relations=[
            _rel("connected_to", "road_001", "bridge_001"),
            _rel("connected_to", "bridge_001", "road_002"),
            _rel("near", "house_001", "house_002"),
        ],
    )
    snow = WorldState(
        scene="snow_castle",
        map=MapSpec(biome="snow"),
        objects=[
            _obj("castle", 1, 11, 4, 9, 7, "ice"),
            _obj("tower", 1, 6, 5, 3, 4, "ice"),
            _obj("tower", 2, 23, 5, 3, 4, "ice"),
            _obj("road", 1, 14, 11, 3, 12),
            _obj("npc", 1, 12, 12),
            _obj("npc", 2, 18, 12),
            _obj("rock", 1, 4, 16, 2, 2),
            _obj("rock", 2, 24, 17, 2, 2),
            _obj("rock", 3, 27, 12),
            *[
                _obj("tree", n, x, y, style="frost")
                for n, (x, y) in enumerate([(2, 2), (28, 2), (5, 21), (25, 21), (8, 17)], 1)
            ],
        ],
        relations=[
            _rel("connected_to", "road_001", "castle_001"),
            _rel("near", "tower_001", "castle_001"),
            _rel("near", "npc_001", "castle_001"),
        ],
    )
    desert = WorldState(
        scene="desert_ruins",
        map=MapSpec(biome="desert"),
        objects=[
            _obj("dune", 1, 2, 2, 8, 4),
            _obj("dune", 2, 23, 17, 7, 4),
            _obj("ruin", 1, 5, 10, 4, 4),
            _obj("ruin", 2, 13, 6, 5, 4),
            _obj("ruin", 3, 19, 14, 3, 4),
            _obj("portal", 1, 25, 7, 2, 3),
            _obj("monster", 1, 10, 13),
            _obj("monster", 2, 23, 10),
            _obj("rock", 1, 3, 19),
            _obj("rock", 2, 15, 19),
            _obj("rock", 3, 21, 3),
        ],
        relations=[
            _rel("near", "monster_001", "ruin_001"),
            _rel("near", "monster_002", "portal_001"),
        ],
    )
    city = WorldState(
        scene="apocalyptic_city",
        map=MapSpec(biome="city"),
        objects=[
            _obj("road", 1, 0, 11, 16, 3),
            _obj("road", 2, 16, 11, 16, 3),
            _obj("house", 1, 3, 3, 5, 5, "abandoned"),
            _obj("house", 2, 19, 3, 5, 5, "abandoned"),
            _obj("house", 3, 5, 17, 5, 5, "abandoned"),
            _obj("house", 4, 22, 17, 5, 5, "abandoned"),
            _obj("vehicle", 1, 5, 12, 2, 1),
            _obj("vehicle", 2, 15, 12, 2, 1),
            _obj("vehicle", 3, 26, 12, 2, 1),
            _obj("monster", 1, 10, 8),
            _obj("monster", 2, 19, 15),
            _obj("monster", 3, 29, 7),
            _obj("rock", 1, 13, 4),
            _obj("rock", 2, 15, 20),
        ],
        relations=[
            _rel("connected_to", "road_001", "road_002"),
            _rel("near", "monster_001", "house_001"),
        ],
    )
    academy = WorldState(
        scene="magic_academy",
        map=MapSpec(biome="arcane"),
        objects=[
            _obj("courtyard", 1, 9, 10, 14, 10),
            _obj("library", 1, 12, 3, 8, 5, "gothic"),
            _obj("tower", 1, 3, 7, 3, 5),
            _obj("tower", 2, 26, 7, 3, 5),
            _obj("portal", 1, 15, 11, 2, 3),
            _obj("crystal", 1, 11, 15),
            _obj("crystal", 2, 20, 15),
            _obj("crystal", 3, 16, 18),
            _obj("npc", 1, 13, 17),
            _obj("npc", 2, 19, 17),
            _obj("tree", 1, 5, 18),
            _obj("tree", 2, 27, 18),
        ],
        relations=[
            _rel("inside", "npc_001", "courtyard_001"),
            _rel("inside", "npc_002", "courtyard_001"),
            _rel("inside", "portal_001", "courtyard_001"),
            _rel("near", "npc_001", "crystal_001"),
        ],
    )
    return {world.scene: world for world in (forest, snow, desert, city, academy)}
